on: [push, pull_request]

name: Continuous integration

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust:
                    - stable
                    - nightly
                    - 1.43.0 # lowest supported version
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --all-features

    test:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust:
                    - stable
                    - nightly
                    - 1.43.0 # lowest supported version
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --all-features

    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: rustfmt
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust:
                    - stable
                    - nightly
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
                  components: clippy
            - uses: actions-rs/clippy-check@v1
              with:
                  name: Clippy-${{ matrix.rust }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-features

    fuzz:
        name: libFuzzer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              name: Cache corpus
              id: cache-corpus
              with:
                  path: fuzz/corpus
                  key: fuzz-corpus
            - uses: actions/cache@v1
              name: Cache artifacts
              id: cache-artifacts
              with:
                  path: fuzz/artifacts
                  key: fuzz-artifacts
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly
                  override: true
            - uses: actions-rs/install@v0.1
              with:
                  crate: cargo-fuzz
                  version: latest
            - run: cargo fuzz run palmtree -- -max_total_time=600 # fuzz for 10 minutes
